<<<<<<< HEAD:migrations/versions/bd237f15f82b_comments_add.py
"""comments add

Revision ID: bd237f15f82b
Revises: 5dc07db7f54f
Create Date: 2021-07-09 12:35:37.326367
=======
"""creatingcomment  tables

Revision ID: a3babe1ecb13
Revises: 5dc07db7f54f
Create Date: 2021-07-09 11:39:31.185839
>>>>>>> 85c6df7c9589bca88266f24478ff3edc519101e1:migrations/versions/a3babe1ecb13_creatingcomment_tables.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/bd237f15f82b_comments_add.py
revision = 'bd237f15f82b'
=======
revision = 'a3babe1ecb13'
>>>>>>> 85c6df7c9589bca88266f24478ff3edc519101e1:migrations/versions/a3babe1ecb13_creatingcomment_tables.py
down_revision = '5dc07db7f54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
